apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: user-service-config
spec:
  # Suppress scheduler warnings for services that don't use scheduling features
  features:
    - name: SchedulerReminders
      enabled: false
  tracing:
    samplingRate: '1'
    zipkin:
      endpointAddress: 'http://localhost:9411/api/v2/spans'
